---
- name: When unicast enable, gather facts from hosts regardless of limit or tags
  block:
    - name: "Get fact for {{ item }}"
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      when: hostvars[item]['ansible_default_ipv4'] is not defined
      with_items:
        - "{{ keepalived_master }}"
        - "{{ keepalived_backup }}"
  
  when: keepalived_unicast|default(false)|bool

- name: Main configuration file from template
  template:
    src: "keepalived.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"
  notify: restart keepalived

#dedicated logfile
- name: Dedicated logfile if keepalived_logfile is defined
  block:
    - name: Set logfacility 6 in keepalived options
      replace:
        path: /etc/sysconfig/keepalived
        regexp: '^KEEPALIVED_OPTIONS=.*$'
        replace: 'KEEPALIVED_OPTIONS="-D --log-facility=6"'
      notify: restart keepalived

    - name: Rsyslog conf for keepalived
      copy:
        content: "local6.* {{ keepalived_logfile }}"
        dest: "/etc/rsyslog.d/keepalived.conf"
        owner: "root"
        group: "root"
        mode: 0644
      notify: restart rsyslog

    - name: Logrotate conf for keepalived
      template:
        src: "keepalived.logrotate.j2"
        dest: "/etc/logrotate.d/keepalived"
        owner: "root"
        group: "root"
        mode: 0644

  when: keepalived_logfile is defined

#network conf for ha mode
- name: NAT configuration when high availability mode is enable
  block:
    - name: Ensure conntrack is enabled
      sysctl:
        name: net.ipv4.vs.conntrack
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: Ensure LVS module is loaded at boot
      copy:
        content: "ip_vs"
        dest: "/etc/modules-load.d/lvs.conf"
        owner: "root"
        group: "root"
        mode: 0644

    - name: Enable masquerade
      firewalld:
        zone: trusted
        masquerade: yes
        state: enabled
        permanent: yes

  when: keepalived_mode == "ha"
