---
- name: Install required RPMs
  yum:
    name:
      - keepalived
      - ipvsadm
    state: present
    update_cache: yes

- name: Enable keepalived on boot
  systemd:
    name: keepalived
    enabled: yes

