---
- name: Install required RPMs
  yum:
    name:
      - keepalived
      - ipvsadm
    state: present
    update_cache: yes

- name: Enable keepalived on boot
  systemd:
    name: keepalived
    enabled: yes

- name: Copy check scripts files to /etc/keepalived
  copy:
    src: "{{ item }}"
    dest: "/etc/keepalived/"
    owner: "root"
    group: "root"
    mode: 0755
  with_fileglob: "check_*"

