---
# tasks file for balancer-ansible-role

- name: Install LVS balancer
  include: install.yml
  when: keepalived_state == "present"

- name: Uninstall LVS balancer
  include: uninstall.yml
  when: keepalived_state == "absent"
