---
# handlers file for simple-keepalived-ansible-role
- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: read conntrack
  shell: /sbin/sysctl -p /etc/sysctl.d/conntrack.conf
